# SPDX-FileCopyrightText: 2020 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

jobs:
  build:
    name: Build
    runs-on: windows-latest

    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: write
      id-token: write
      attestations: write

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE: true

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          cache: true
          cache-dependency-path: |
            global.json
            '**/packages.lock.json'

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet restore Installer

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore --property:Platform=x64 --binaryLogger:build-x64.binlog
          dotnet build --configuration Release --no-restore --property:Platform=ARM64 Usbipd --binaryLogger:build-arm64.binlog

      - name: Test
        run: |
          dotnet test --configuration Release --no-build --property:Platform=x64 `
            --report-spekt-junit `
            --coverage --coverage-output-format cobertura

      - name: Build x64 Installer
        run: |
          dotnet publish --configuration Release --no-build --runtime win-x64 --property:PublishProfile=x64 Usbipd --binaryLogger:publish-x64.binlog
          dotnet publish --configuration Release --no-build Usbipd.PowerShell --binaryLogger:publish-PowerShell.binlog
          dotnet build --configuration Release --no-restore --property:Platform=x64 Installer --binaryLogger:installer-x64.binlog

      - name: Build arm64 Installer
        run: |
          dotnet publish --configuration Release --no-build --runtime win-arm64 --property:PublishProfile=arm64 Usbipd --binaryLogger:publish-arm64.binlog
          dotnet build --configuration Release --no-restore --property:Platform=ARM64 Installer --binaryLogger:installer-arm64.binlog

      # GitHub will always zip the artifacts and add .zip to the filename.
      # Therefore, it makes no sense to upload individual .msi files. We always upload everything as a single artifacts container.
      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: 'Installer/bin/*/release/*.msi'

      - name: Build Attestation
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-name: artifacts.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          report_type: test_results
          files: TestResults/TestResults.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          files: TestResults/*.cobertura.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Submit Dependencies to GitHub
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: advanced-security/component-detection-dependency-submission-action@31f25a8de68ae5ce2ca274bc28546a78683c15ce # v0.1.4
        with:
          detectorArgs: MSBuildBinaryLog=Enable
          detectorsFilter: MSBuildBinaryLog

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: always
