# SPDX-FileCopyrightText: 2023 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: usb.ids

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - name: Check for new usb.ids
        run: |
          curl --fail --output Usbipd.Automation/usb.ids http://www.linux-usb.org/usb.ids # DevSkim: ignore DS137138

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Update usb.ids'
          title: 'Update usb.ids'
          branch: update-usbids
          body: |
            This is an automated pull request, updating `usb.ids` after a detected change.
            Please review manually before merging.
