# SPDX-FileCopyrightText: 2023 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: winget

on:
  workflow_dispatch:
  release:
    types: [released]

permissions: {}

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: WinGet Releaser
        uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: dorssel.usbipd-win
          token: ${{ secrets.WINGET_TOKEN }}
