# SPDX-FileCopyrightText: 2023 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: winget

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag'
        required: true
        type: string
  release:
    types: [released]

permissions: read-all

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: dorssel.usbipd-win
          release-tag: ${{ github.event.release.tag_name || inputs.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
